import Head from 'next/head'
import FormImage from '../../public/form.png'
import Image from 'next/image'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import { motion as m } from 'framer-motion'


export default function Home() {
  const router = useRouter()

  // formik logic
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Nigeria",
      terms: "",
    },

    // Validate form
    validationSchema: Yup.object({
      name: Yup.string().max(20, 'Name must be 20 characters or less.').required('Name is required'),
      email: Yup.string()
        .email('Invalid email address')
        .required('Email is required'),
      terms: Yup.array().min(1).required("Terms of service must be checked")
    }),

    // submit form
    onSubmit: (values) => {
      console.log(values)
      router.push({ pathname: '/success', query: values })
    },
  })


  return (
    <m.div
      initial={{ opacity: 0 }}
      exit={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className='absolute w-full'
    >
      <Head>
        <title>Form app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">

        <form onSubmit={formik.handleSubmit} className='bg-white  rounded-lg w-1/2'>
          {/* <div className='flex-1'>
            <Image alt='form-learn' src={FormImage} className="object-cover rounded-lg" />
          </div> */}
          <div className="flex-1 text-gray-700 py-20 px-10">
            <h1 className='text-3xl pb-2 font-semibold'>Let's get started</h1>
            <p className='text-lg text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

            {/* form */}
            <div className='mt-6'>

              {/* Name input field */}
              <div className="pb-4">
                <label className={`block font-medium pb-2 ${formik.touched.name && formik.errors.name && 'text-red-400'}`} htmlFor="name">
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  className='border-2 border-gray-500 p-2 rounded-md w-full outline-none focus:border-teal-500 focus:ring-teal-500'
                  type="text" name="name" id="" placeholder='Enter your name' />
              </div>

              {/* Email input field */}
              <div className="pb-4">
                <label className={`block font-medium pb-2 ${formik.touched.email && formik.errors.email && 'text-red-400'}`} htmlFor="email">{formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}</label>
                <input
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  className='border-2 border-gray-500 p-2 rounded-md w-full outline-none focus:border-teal-500 focus:ring-teal-500'
                  type="text" name="email" id="" placeholder='Enter your email' />
              </div>

              {/* Country input field */}
              <div className="pb-4">
                <label className='block font-medium pb-2' htmlFor="country">Country</label>
                <select
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  name='country'
                  className='border-2 border-gray-500 p-2 rounded-md w-full outline-none focus:border-teal-500 focus:ring-teal-500'>
                  <option>Ghana</option>
                  <option>Togo</option>
                  <option>Nigeria</option>
                  <option>Egypt</option>
                </select>
              </div>


              {/* terms of service field */}
              <div className="pb-4">
                <label className={`block font-medium pb-2 ${formik.touched.terms && formik.errors.terms && 'text-red-400'}`} htmlFor="terms">{formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of service'}</label>
                <div className='flex gap-2 items-center'>
                  <input
                    onBlur={formik.handleBlur}
                    onChange={formik.handleChange}
                    type="checkbox" name='terms' value="checked" className='h-5 w-5 text-teal-500 border-2 focus:border-teal-500' />
                  <p className='text-sm font-medium text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque.</p>
                </div>
              </div>

              <button type='submit' className='bg-teal-500 text-sm text-white font-semibold mt-6 py-3 rounded-md w-full'>Start learning today</button>
            </div>
          </div>


        </form>
      </main>
    </m.div>
  )
}
